### ISSUE TITLE
Add per-band options

### ISSUE THREAD

**Issue by matthewhanson** [sat-utils/sat-multispectral#12]
There needs to be a way to set options on specific bands, which will then be set on the GeoImage when it is opened.   Specifically these options would include, but are not limited to the nodata value and the gain and offset for the band.

One approach is to have an Options method for the Scene, which will take in options for bands (and return a Scene) so it can be part of the processing chain.

**Comment by scisco** [comment]
Scene is now merely a subclass of geoimage
